### ISSUE TITLE
!!! Please set favorite before usage !!!

### ISSUE THREAD

**Issue by jfmennedy** [dominikkarall/fhempy#10]
V0.1.11

When I try  to play a defined Favorit on GoogleCast Devices (e.g.:attr Google_Home_Mini_Badezimmer favorite_1 http://wdr-1live-live.icecast.wdr.de/wdr/1live/live/mp3/128/stream.mp3
)  I get response 
!!! Please set favorite before usage !!!

**Comment by dominikkarall** [comment]
I hope it's fixed now:
https://github.com/dominikkarall/fhempy/releases/tag/v0.1.12

**Comment by jfmennedy** [comment]
Now it´s working 👍
