### ISSUE TITLE
support tuya heating device

### ISSUE THREAD

**Issue by jfmennedy** [dominikkarall/fhempy#12]
![tuya_iobroker](https://user-images.githubusercontent.com/52569066/104104457-97d16d00-52a8-11eb-87fe-fe3288119941.png)

I know the credentials (Type, Device ID, local Key, IP)  of a tuya device, but I cannot define as followed:

define tuya_device PythonModule tuya Device 0020sae45ccf7f3df1c7 192.168.0.66 1c4f01asdvdsdcf74 [VERSION=3.1]

The entry in the log is :

`Traceback (most recent call last):
  File "/opt/fhem/.local/lib/python3.7/site-packages/tinytuya/__init__.py", line 336, in _send_receive
    data = self.socket.recv(1024)
ConnectionResetError: [Errno 104] Connection reset by peer
2021-01-09 14:35:37,063 - ERROR    - tuya_device: Failed to get current status from device
2021-01-09 14:35:52,454 - ERROR    - tuya_device: Failed to get current status from device
2021-01-09 14:36:08,010 - ERROR    - tinytuya: Exceeded tinytuya retry limit (5)
`

I extracted the informations from the definition in iobroker, where the device is operating.

**Comment by dominikkarall** [comment]
Could it be that the device is connected in iobroker and therefore the connection can't be established by fhempy? Afaik the devices only support one connection.

**Comment by jfmennedy** [comment]
I stopped iobroker and restartet the device, but no connection possible...

**Comment by dominikkarall** [comment]
Ah, I see...[VERSION=3.1] means that it is optional :)
```
define tuya_device PythonModule tuya Device 0020sae45ccf7f3df1c7 192.168.0.66 1c4f01asdvdsdcf74 3.1
```
should work

**Comment by jfmennedy** [comment]
:-) Phanastic :-) I can switch on and off the device. It´s a wall heating device with setpoint and lamella to swing.. Is it possible to get the setpoint also as set command?

This is the definition in iobroker, if this helps:

{
  "type": "device",
  "common": {
    "name": "Konvektor",
    "read": true,
    "write": false
  },
  "native": {
    "ip": "192.168.0.66",
    "gwId": "0.002009asdfcf7f3df1c7",
    "active": 2,
    "ability": 0,
    "mode": 0,
    "encrypt": true,
    "productKey": "QgDtdasdaBJ9g360K",
    "version": "3.1",
    "localKey": "1c4f01aasddacf74",
    "virtual": false,
    "lon": "5.7463082",
    "uuid": "0.002009asdfcf7f3df1c7",
    "iconUrl": "https://images.tuyaeu.com/smart/icon/1502104338_0.png",
    "lat": "49.701845",
    "runtimeEnv": "prod",
    "devId": "0.002009asdfcf7f3df1c7",
    "dpMaxTime": 1552723031750,
    "productId": "QgDtdkPRBJ9g360K",
    "activeTime": 1552722551,
    "moduleMap": {
      "wifi": {
        "upgradeStatus": 0,
        "bv": "5.20",
        "cdv": "",
        "pv": "2.1",
        "verSw": "1.0.5",
        "isOnline": true,
        "id": 5422350,
        "cadv": ""
      },
      "mcu": {
        "upgradeStatus": 0,
        "cdv": "",
        "verSw": "1.0.5",
        "isOnline": true,
        "id": 5424151,
        "cadv": ""
      }
    },
    "devAttribute": 0,
    "name": "Konvektor",
    "timezoneId": "Europe/Brussels",
    "schema": [
      {
        "mode": "rw",
        "code": "Power",
        "name": "开关",
        "property": {
          "type": "bool"
        },
        "iconname": "icon-dp_power2",
        "id": 1,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "rw",
        "code": "TempSet",
        "name": "目标温度",
        "property": {
          "unit": "℃",
          "min": 10,
          "max": 49,
          "scale": 0,
          "step": 1,
          "type": "value"
        },
        "iconname": "icon-dp_temp",
        "id": 2,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "ro",
        "code": "TempCurrent",
        "name": "当前温度",
        "property": {
          "unit": "℃",
          "min": 0,
          "max": 50,
          "scale": 0,
          "step": 1,
          "type": "value"
        },
        "iconname": "icon-dp_sun",
        "id": 3,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "rw",
        "code": "Mode",
        "name": "模式",
        "property": {
          "range": [
            "1",
            "2",
            "off"
          ],
          "type": "enum"
        },
        "iconname": "icon-dp_mode",
        "id": 4,
        "type": "obj",
        "desc": ""
      },
      {
        "mode": "rw",
        "code": "Shake",
        "name": "摇头",
        "property": {
          "type": "bool"
        },
        "iconname": "icon-dp_shake",
        "id": 7,
        "type": "obj",
        "desc": ""
      }
    ],
    "schemaExt": [
      {
        "id": 2,
        "inputType": ""
      },
      {
        "id": 3,
        "inputType": ""
      }
    ]
  },
  "from": "system.adapter.tuya.0",
  "ts": 161021asa0370,
  "_id": "tuya.0.002009asdfcf7f3df1c7",
  "acl": {
    "object": 1636,
    "ownerGroup": "system.group.administrator"
  },
  "user": "system.user.admin"
}

**Comment by dominikkarall** [comment]
Everything should be possible ;)

I'll check how to integrate. Do you see on_switch_2, etc. in the current FHEM device?
Have you had to configure it to be able to control it, or was it autodiscovered in iobroker?

**Comment by jfmennedy** [comment]
Yes  i see on/off_switch_2 _3 _4 and _7.. 

4 seems to be the mode (enum 0,1,2) and 7  the shake of lamella , (on/off).. 2 is the setpoint and 3 the current temp.

it was auto-discovered in iobroker, respectively there seems to be templates for different devices...

**Comment by dominikkarall** [comment]
Thanks, I found the mappings in iobroker. That's great as I was searching already for some sort of tuya mapping based on product key.

I'll have a look how to implement it.

**Comment by dominikkarall** [comment]
Please test release v0.1.24. Keep in mind that the define statement changed, as it includes the product id now.

See https://github.com/dominikkarall/fhempy/blob/master/FHEM/bindings/python/fhempy/lib/tuya/README.md#individual-device

**Comment by jfmennedy** [comment]
![Tuya_HeatingDevice](https://user-images.githubusercontent.com/52569066/105337914-3af48180-5bdb-11eb-91ea-13db1e35d25f.png)

Looks great and works fine :-) Thank You

**Comment by jfmennedy** [comment]
Just one remark, the state is "PythonBinding offline" but the binding is working as the other python modules (googlecast and spotify)..

**Comment by dominikkarall** [comment]
Perfect! 👍

Ah, the PythonBinding offline state is because state is not used for your heater and therefore it remains offline, even if it's actually not offline. I'm going to fix it and set state to online and offline when the device can't be reached.

**Comment by jfmennedy** [comment]
Great :-)

These are the attributes if you or someone else want to use them to set up the device as shown in the screenshot:

attr tuya_heatdevice icon vent_used_air
attr tuya_heatdevice stateFormat Istwert: TempCurrent°C <br/> Sollwert: TempSet°C <br/> Schalter: Power <br/> Stufe: Mode <br/> Lamellen: Shake
attr tuya_heatdevice webCmd Power:TempSet:Mode:Shake
attr tuya_heatdevice webCmdLabel Schalter\
:Sollwert\
:Stufe\
:Lamellen

**Comment by dominikkarall** [comment]
Please test with v0.1.25 if state is now properly handled. Should show online/offline.

**Comment by jfmennedy** [comment]
👍 Status is going online.. We might close this

**Comment by dominikkarall** [comment]
👍
