### ISSUE TITLE
Tuya New Heating Device

### ISSUE THREAD

**Issue by jfmennedy** [dominikkarall/fhempy#13]
I got another Heating Device with Tuya. It is defined and I got the readings but no set commands get installed. 

This is the list of the device:

Internals:
   DEF        tuya 20qAGCEd0AxowwTA xxxxxxxxxxxxxxxxxxxxxx 192.168.0.141 xxxxxxxxxxxxxx 3.1
   DEVICEID   xxxxxxxxxxxxxxxxxxxxxx 
   FUUID      60140eb4-f33f-7f5e-e600-20f4df6d0e174850
   IODev      local_pybinding
   NAME       wz_Heizkonvektor
   NR         2039
   PYTHONTYPE tuya
   STATE      online
   TYPE       PythonModule
   READINGS:
     2021-01-29 14:33:57   dp_01           1
     2021-01-29 14:57:51   dp_02           25
     2021-01-29 15:34:55   dp_03           21
     2021-01-29 14:50:12   dp_04           p
     2021-01-29 15:06:41   dp_101          mid
     2021-01-29 14:46:06   dp_102          0
     2021-01-29 14:33:57   dp_12           0
     2021-01-29 14:34:19   state           online
   args:
     wz_Heizkonvektor
     PythonModule
     tuya
     20qAGCEd0AxowwTA
     xxxxxxxxxxxxxxxxxxxxxx 
     192.168.0.141
     xxxxxxxxxxxxxxxxxxx
     3.1
   argsh:
Attributes:
   DbLogExclude .*
   IODev      local_pybinding
   alias      Heizkonvektor
   group      Heizung
   icon       sani_floor_heating
   interval   5
   keep_connected on
   room       21_Wohnzimmer,61_Heizung

The Mappings are the follwing values:

   dp_01           power on (1) off (0)
   dp_02           targetTemp
   dp_03           actualTemp
   dp_04           mode manu (m) auto (p)
   dp_101         setting off low mid high
   dp_102         standby (eco) on (1) off (0)
   dp_12           0 unknown

**Comment by dominikkarall** [comment]
I'm going to implement it later today.

**Comment by dominikkarall** [comment]
I implemented it with the names you mentioned above. Is standby_eco correct for dp_102 or did I misunderstood that? Please test with v0.1.39.

**Comment by jfmennedy** [comment]
Wow great every single command is set to the device 👍👍👍 the Eco standby is OK like this.. When it's on the heater is set to 16 deg as like a freeze protection for the room...

**Comment by jfmennedy** [comment]
BTW I might to have kill sth with all testing at me.. For doing an update I Need to remove the folder /opt/fhem/.local/lib/python3.7 and restart the binging...

**Comment by jfmennedy** [comment]
![Uploading tuya_heating.png…]()
but looks good ;-)
