### ISSUE TITLE
Ring Doorbell Downgrade to 0.6.2

### ISSUE THREAD

**Issue by jfmennedy** [dominikkarall/fhempy#14]
Hi, 

could you please downgrade the requirements to version 0.6.2 of ring_doorbell.. There is a bug in the current version of 0.7.0 (https://github.com/tchellomello/python-ring-doorbell/issues/240)

Thx, Jan

**Comment by dominikkarall** [comment]
Hi Jan,

thx for the info. I reverted back to 0.6.2.

New release: 0.1.56
