### ISSUE TITLE
Skoda Connect Implementation

### ISSUE THREAD

**Issue by jfmennedy** [dominikkarall/fhempy#16]
Hi, 

might it be possible to integrate this library https://github.com/lendy007/skodaconnect 

Thanks Jan

**Comment by dominikkarall** [comment]
The API looks pretty straight forward. That shouldn't be a problem to implement. Unfortunately I can't buy a "testdevice" ;)

Have you tested the example to see if it works for you:
https://github.com/lendy007/skodaconnect/blob/main/example/example.py

**Comment by jfmennedy** [comment]
I unfortunatly crashed my whole server system 2 weeks ago.. Crash of raid controller.. Still recovering data.. All my test Environments are still not operational 🥲 if it would help I could share my car with you...

**Comment by jfmennedy** [comment]
The example is working for me. The script makes a login and fetches vehicle data. There just seems to be a problem with the token, but this may be my environment (Failed to verify connect token, error: module 'jwt.algorithms' has no attribute 'RSAAlgorithm')

**Comment by dominikkarall** [comment]
Great, would you share your login via email? I would give it a try and would only retrieve values from the car.

**Comment by dominikkarall** [comment]
Hi Jan,
please test with the latest version :)
Thanks for providing me your car for testing!

**Comment by dominikkarall** [comment]
Just to inform everybody who reads this. skodaconnect will work as soon as the skodaconnect packages is updated, see:
https://github.com/lendy007/skodaconnect/issues/18

**Comment by jfmennedy** [comment]
We might close. 1.0.42 from lendy007/skodaconnect is out and working. The module works fine for my car. Perhaps i will ask in fhem forum to test, so electric cars might be tested too, as mine is not electric...

**Comment by dominikkarall** [comment]
Released with 0.1.66, thanks!
