### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by jfmennedy** [dominikkarall/fhempy#27]
After latest update to 0.1.102 fhempy is stuck with error:
`2021-08-28 19:32:42,816 - INFO     - __main__: Attempting install of fhempy>=0.1.12
2021-08-28 19:32:45,251 - INFO     - __main__: Successfully installed fhempy>=0.1.12
2021-08-28 19:32:45,257 - ERROR    - __main__: Failed to import fhempy, exit now...`

**Comment by dominikkarall** [comment]
Argh....zeroconf update was missing in the requirements. Sorry!

Please do
```
sudo -u fhem pip3 install zeroconf==0.36.0
```

I fixed it in version 0.1.103. I'll keep this issue open for one day so that others can easily find it.

**Comment by jfmennedy** [comment]
funny.. it stopped at +/- 20:15 without doing anything... this was +/- the time you posted...  0.1.103 was installed automaticly... perhaps due to `Attempting install of fhempy>=0.1.12` which was running in a loop...

**Comment by dominikkarall** [comment]
You are right! I wasn't even aware of that cool feature I implemented 😆

**Comment by jfmennedy** [comment]
🥇 might be closed
