### ISSUE TITLE
PDFplumber install

### ISSUE THREAD

**Issue by anasus-uk** [dominikkarall/fhempy#33]
Hello,

I am new to coding and I am trying to install PDFplumber to extract some info from pdf files. 
I am using the command !pip install pdfplumber but I am getting the following error - Command "python setup.py egg_info" failed with error code 1. Any ideas of what I may be doing wrong. Any help is much appreciated. Thanks

**Comment by Heiner1967** [comment]
Hi, 
seems to be the same problem like mine, at least the log entry is the same

**Comment by dominikkarall** [comment]
How is this issue related to fhempy? Please reopen if you have a question related to fhempy.
