### ISSUE TITLE
eq3bt: pythonbinding installation

### ISSUE THREAD

**Issue by royweijers1981** [dominikkarall/fhempy#4]
Good afternoon,

Thanks for your previous help. However, it now works after the thermostat. I did what is in the message, but unfortunately does not work. I also get the following message:

![image](https://user-images.githubusercontent.com/50567466/97573602-4e33ee80-19ea-11eb-9270-c96c345d83c0.png)

Now it is also true that if I want to set the temperature I get the message below.

Can you help me with the last problem?

thank you

![image](https://user-images.githubusercontent.com/50567466/97573695-77ed1580-19ea-11eb-9cfa-dd30d858a2a6.png)
![image](https://user-images.githubusercontent.com/50567466/97590683-2733e780-19ff-11eb-852e-79e5e73d7a45.png)

**Comment by royweijers1981** [comment]
below some more information if that is useful

![image](https://user-images.githubusercontent.com/50567466/97574038-ee8a1300-19ea-11eb-8da0-cb86009565d4.png)
![image](https://user-images.githubusercontent.com/50567466/97574177-1f6a4800-19eb-11eb-8ddb-42c9e5721669.png)
![image](https://user-images.githubusercontent.com/50567466/97574266-40cb3400-19eb-11eb-961f-8317a57aab46.png)
![image](https://user-images.githubusercontent.com/50567466/97574329-57718b00-19eb-11eb-8742-d1b8612a77b1.png)

**Comment by royweijers1981** [comment]
'm a bit further. Now it is still that it has time-out including the message when I want to set the temperature


![image](https://user-images.githubusercontent.com/50567466/97577646-f9937200-19ef-11eb-8744-340fc5a005ea.png)

**Comment by royweijers1981** [comment]
I think it has to do with rights. Can you indicate which files should have which user and group?
below where the folders are.
1. /etc/ststemd.system fhem_pythonbinding.servcie
2.
/ root / fhem_pythonbinding
3. / home / pi / fhem_pythonbinding
4.
/ opt / fhem / FHEM / bindings
5.
/ etc / dbus-1

Thanks I can check this first

thank you in advance

**Comment by royweijers1981** [comment]
When I turn on the thermostat now I get the message below

Failed to execute function Set: Traceback (most recent call last):
  File "/home/pi/fhem_pythonbinding/FHEM/bindings/python/lib/fhem_pythonbinding.py", line 236, in _onMessage
    ret = await asyncio.wait_for(func(hash, hash['args'], hash['argsh']), fct_timeout)
  File "/usr/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/home/pi/fhem_pythonbinding/FHEM/bindings/python/lib/eq3bt/eq3bt.py", line 122, in Set
    return await utils.handle_set(self.set_list_conf, self, hash, args, argsh)
  File "/home/pi/fhem_pythonbinding/FHEM/bindings/python/lib/utils.py", line 167, in handle_set
    return await fct_call(hash)
  File "/home/pi/fhem_pythonbinding/FHEM/bindings/python/lib/eq3bt/eq3bt.py", line 196, in set_on
    asyncio.create_task(self.set_and_update(functools.partial(self.thermostat.set_target_temperature, 30)))
AttributeError: 'eq3bt' object has no attribute 'thermostat'

**Comment by dominikkarall** [comment]
Please let me know if this issue can be closed.

**Comment by royweijers1981** [comment]
> Please let me know if this issue can be closed.

Hello, thanks for your response, I'm going to check it now.

**Comment by royweijers1981** [comment]
Hello,

Here I am again.
He keeps saying the same. I changed fhem to pi in the config file. am I supposed to change the user of the file to pi?

**Comment by dominikkarall** [comment]
Ok, please provide me more info:
 - Do you run the installation on the same device as FHEM is installed on?
 - Why did you install fhem_pythonbinding in /root and /home/pi?
 - Why did you install fhem_pythonbinding.service when you want to use it on your FHEM installation?

Please let me know which parts of the readme were confusing so that I can adapt them. Which parts of the commands in the readme did you execute?

**Comment by royweijers1981** [comment]
> Oké, geef me alsjeblieft meer informatie:
> 
> * Voert u de installatie uit op hetzelfde apparaat als waarop FHEM is geïnstalleerd?
> * Waarom heb je fhem_pythonbinding in / root en / home / pi geïnstalleerd?
> * Waarom heb je fhem_pythonbinding.service geïnstalleerd als je het op je FHEM-installatie wilt gebruiken?
> 
> Laat me alsjeblieft weten welke delen van het leesmij-bestand verwarrend waren, zodat ik ze kan aanpassen. Welke delen van de opdrachten in het leesmij-bestand heb je uitgevoerd?


Hello,

* yes correct, this is installed on the same device.
* the installation did that automatically ... do I understand that it can be removed from the root folder?
* this was also done automatically.

* Incidentally, I have followed the installation which is indicated in your code. do I understand well that I can delete part? the chromecast works quite well

**Comment by dominikkarall** [comment]
I assume you run the code mentioned here
https://github.com/dominikkarall/fhem_pythonbinding#configure-remote-python-peers-eg-extend-bluetooth-range

This is only needed if you want remote peers (like a separate rpi to extend bluetooth range). I will update the readme to make that clear.

 - Please remove all the /root /home/pi and /etc/systemd/... files which you installed, they are not needed.
 - Please change again the bluetooth.conf file to user "fhem" if you run FHEM with the user fhem.
 - Restart the system afterwards to make sure that the proper fhem_pythonbinding (started by FHEM) runs

Let me know if that works for you.

**Comment by royweijers1981** [comment]
I have implemented your link idd.

* files have been deleted
* how do you mean this rule?
do you mean this fhem below?

![image](https://user-images.githubusercontent.com/50567466/98171782-95414880-1ef0-11eb-8a5d-14b2c7758cef.png)


of these 

![image](https://user-images.githubusercontent.com/50567466/98171893-bb66e880-1ef0-11eb-9c05-e3cc998267ef.png)

**Comment by dominikkarall** [comment]
Everything is installed under /opt/fhem if that is your working fhem directory. Those files should not be touched. You can remove /home/pi/fhem_pythonbinding.

I didn't get your question, what do you mean with rule?

**Comment by dominikkarall** [comment]
Did you manage the installation?

**Comment by royweijers1981** [comment]
> Did you manage the installation?


Hello, sorry was just a weekend away. ;-) Yes I have. But don't get it working properly. Does this also apply to the nest thermostat?

**Comment by royweijers1981** [comment]
> Heeft u de installatie beheerd?

yes i Did

**Comment by dominikkarall** [comment]
> > Did you manage the installation?
> 
> Hello, sorry was just a weekend away. ;-) Yes I have. But don't get it working properly.

What's not working?

**Comment by VinceMasuka** [comment]
@royweijers1981 
I had pretty much the same issue than you. In my case the bluetooth usb dongle just hang and
```
sudo hcitool dev
```
just brought nothing up. After fixing bluetooth the pythonbinding just worked flawlessly.

If that's not the case:
In my humble opinion you shouldn't alter any user on the files, as the installation procedure just does not tell you so (and the steps just don't indicate that it's needed).

Perhaps you want to make sure, that on remote peer file
```
/etc/dbus-1/system.d/bluetooth.conf
```
has this block in it:
```
                        <policy user="pi">
                            <allow own="org.bluez"/>
                            <allow send_destination="org.bluez"/>
                            <allow send_interface="org.bluez.GattCharacteristic1"/>
                            <allow send_interface="org.bluez.GattDescriptor1"/>
                            <allow send_interface="org.freedesktop.DBus.ObjectManager"/>
                            <allow send_interface="org.freedesktop.DBus.Properties"/>
                        </policy>
```
(in my case I log into my remote peer as user "pi", that's why pi is stated above, as I did the installation procedure with this user)
As stated in the installation procedure "add" this block. There is no indication to replace any existing block. Perhaps you just put in beneath the existing one...

Don't forget to restart the dbus service afterwards.

**Comment by dominikkarall** [comment]
Closing due to no more updates. If you have any issues, feel free to open a new issue.
