### ISSUE TITLE
eq3bt - windowOpenTime & windowOpenTemperature does not work.

### ISSUE THREAD

**Issue by JorinL** [dominikkarall/fhempy#45]
Hey there :-)

The setting of "windowOpenTime" and "windowOpenTemperature" does not function.
The values of both do not change. 

I do not see an error inside the log - but I'll take deeper look.

Tested with 0.1.183

**Comment by dominikkarall** [comment]
Finally fixed :)

Please check with version 0.1.184: https://github.com/dominikkarall/fhempy/releases/tag/v0.1.184

**Comment by JorinL** [comment]
Looks very good -> found eventually one thing: windowOpentemperature 4.5 is not working - all others are ;-D 

WindowOpenTime is smooth working :-)
Thank you very much.

**Comment by dominikkarall** [comment]
Do you know if 4.5 (OFF) is supported on the thermostat and in the calorBT app?

**Comment by JorinL** [comment]
Yes I do know, that they definetly do NOT support 4.5 °C on windowOpenTemperature :-D 
Even on the unit it is NOT supported with 4.5 °C :-D

Did not know that until now. :-D

All works fine - perfect!

Thank you!
