### ISSUE TITLE
Got some unclear problems with a peer (I think)

### ISSUE THREAD

**Issue by JorinL** [dominikkarall/fhempy#47]
![image](https://user-images.githubusercontent.com/33031729/145289153-e5da5351-e7ec-4ded-9c60-22f630eff117.png)

Are you able to help me? :-D

I just wanted to newly install/reinstall the fhempypeer on that unit -> did not work as it looks O_o

Set temperature generates this error in FHEM.

**Comment by dominikkarall** [comment]
It looks like the peer didn't connect to the thermostat yet. Try to wait for 2 minutes until you send the set command.

Btw, Peers don't save any data. So reinstall is definitely not needed, you can just send an update via FHEM / BindingsIo device.

**Comment by JorinL** [comment]
Reinstall = I did delete the installation before :-D

**Comment by JorinL** [comment]
Oh found something:
![image](https://user-images.githubusercontent.com/33031729/145290740-7a8ff45d-c574-485e-b9e7-dbb85c1a8a87.png)

**Comment by JorinL** [comment]
Mh I did so (nothing new that info) but won't go away and connect O_o user is pi (raspi 3b+ peer).
