### ISSUE TITLE
Modul pyit600 implementation

### ISSUE THREAD

**Issue by staeblvo** [dominikkarall/fhempy#51]
Hi,
ich habe begonnen das Modul pyit600 (https://github.com/jvitkauskas/pyit600) bei mir in fhempy zu integrieren.
In meiner Implementierung wird aber nur das Gerät VS20WRF von Salus iT600 unterstützt, da ich keine anderes zum Testen habe.
Getestet habe ich das mit diesem Setup: UGE600, 2xKL08RF und 9xVS20WRF.

Hier meine Implementierung:
[pyit600.zip](https://github.com/dominikkarall/fhempy/files/7820692/pyit600.zip)

Evtl. lohnt es sich ja schon, das "offiziell" in fhempy aufzunehmen.?

Gruß
Volker

**Comment by dominikkarall** [comment]
Hi,

super! Gerne schau ich mir nächste Woche den Code an und nehme es dann mit auf.
Du kannst natürlich gerne auch selber einen Pull Request erstellen, dann merge ich es.

Gruß
Dominik

**Comment by dominikkarall** [comment]
Merged, danke dir! 👍
