### ISSUE TITLE
[Eq3bt] Make "maxRetries" available as attribute in FHEM for the user

### ISSUE THREAD

**Issue by JorinL** [dominikkarall/fhempy#61]
It would be nice to have "maxRetries" available as attribute of eq3bt devices in FHEM for the user.
So that we can set it higher or lower depending on connection problems or distance to the device :-)

Would that be possible?

**Comment by dominikkarall** [comment]
Sure, but let me know in which module? 😄

**Comment by JorinL** [comment]
Oh - lol.

Eq3bt 😄😉🙃🙂

**Comment by dominikkarall** [comment]
Bitte Version 0.1.212 testen:
https://github.com/dominikkarall/fhempy/releases/tag/v0.1.212

**Comment by JorinL** [comment]
Top -> looks good -> testing :-)

Thank you!

**Comment by JorinL** [comment]
Yup - would say :-)  
Done - Thank you!
