### ISSUE TITLE
Ring chime device IO Device fhempy_peer not settable

### ISSUE THREAD

**Issue by jfmennedy** [dominikkarall/fhempy#66]
When I try to set a fhempy Peer as IO Device I got pop up response "continue" and the IO Device is not set and remains local_pybinding

**Comment by dominikkarall** [comment]
Does that happen only for the ring module? Is it working for others?

**Comment by jfmennedy** [comment]
It does not work only for the chime device of the ring module. The doorbells of ring module are working and also all other on my installation (googlecast, spotify, skodaconnect, tuya local, tuya cloud) It is just the chime on ring module...

**Comment by dominikkarall** [comment]
Is there anything visible in the fhempy log file? Can you do the change with verbose 5 for that device and check the log?

**Comment by jfmennedy** [comment]
I switched to verbose 5 for the ring device and for fhempyserver device now. I changed the IO device from local to peer, same message "continue" but now the IO device stays on peer... And it seems to work.. wondering... I tried this so many times because this device was the last remaining local... So it is on peer also now, may I just remove the local fhempy device or also the fhempyserver device from my fhem installation? 

BTW these are the log entries for the switch from local to peer:

Fhem.log :

2022.02.16 20:56:52.141 1: BindingsIo (fhempy_peer_192_168_0_173): ERROR: Timeout while waiting for function to finish (id: 1225450)
2022.02.16 20:56:52.141 1:   NAME =>  ringdev3
2022.02.16 20:56:52.142 1:   id =>  1225450
2022.02.16 20:56:52.142 1:   FHEMPYTYPE =>  ring
2022.02.16 20:56:52.142 1:   PYTHONTYPE =>  ring
2022.02.16 20:56:52.142 1:   defargsh =>  HASH(0x55a5cf4c93b0)
2022.02.16 20:56:52.142 1:   msgtype =>  function
2022.02.16 20:56:52.143 1:   argsh =>  HASH(0x55a5d55070b8)
2022.02.16 20:56:52.143 1:   function =>  Undefine
2022.02.16 20:56:52.143 1:   args =>  ARRAY(0x55a5d4a8ff38)
2022.02.16 20:56:52.144 1:   defargs =>  ARRAY(0x55a5cf4c9548)


FhemPy.log:

2022-02-16 20:52:59,129 - DEBUG    - ringdev3: Received dings: []
2022-02-16 20:53:59,711 - DEBUG    - ringdev3: Received dings: []

Cheers Jan

**Comment by dominikkarall** [comment]
Thx for the log. So it's the Undefine function which caused that issues. I assume it's the part where the thread is cancelled. I'll have a look into it.

If you don't have any devices which rely on the local fhempy you can just stop the fhempyserver_15733, delete it and after that delete the local_pybinding.

**Comment by jfmennedy** [comment]
This was the last device on local.. I always had a problem on shutdown restart after an update of fhem. The fhempy process did not stop so I had to pkill the process.. My fhem is on docker and my peer is an dedicated vm on debian bullseye.. On this constellation it runs absolutely perfect for me...
