### ISSUE TITLE
esphome stopped

### ISSUE THREAD

**Issue by Ice81** [dominikkarall/fhempy#70]
Hello, I was able to install Fhempy without any problems, the server and also the Local Binding are green in  Fhem. I now wanted to install the ESPHome in Fhem, unfortunately this does not work. A new room ESPhome is created, but in the window it only says "Connection was rejected". 
I also don't get an error in Verbose 5.
Has anyone had this problem ?

VG
Ralf

**Comment by dominikkarall** [comment]
Hi,
check if esphome process is running with ps -efa on the Linux console.

**Comment by Ice81** [comment]
Hi,
I'm afraid I don't see the process.
Did I understand correctly that I do not need to install the Home Assistant?

**Comment by dominikkarall** [comment]
Yes, no need to install Home Assistant.

What happens if you use the start command in FHEM for the esphome device?

**Comment by Ice81** [comment]
Nothing ,
 nothing changes. The status remains at stopped

**Comment by dominikkarall** [comment]
Please check the /opt/fhem/.local/bin if there is a esphome file.

**Comment by dominikkarall** [comment]
If not, you might try
sudo -u fhem bash
pip3 install esphome

**Comment by Ice81** [comment]
I try to Install esphome, but the Installer say, it is already installed:

`fhem@raspberrypi:~$ pip3 install esphome                                        Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple    Requirement already satisfied: esphome in ./.local/lib/python3.7/site-packages (2021.9.3)                                                                       Requirement already satisfied: colorama==0.4.4 in ./.local/lib/python3.7/site-packages (from esphome) (0.4.4)                                                   Requirement already satisfied: PyYAML==5.4.1 in /usr/local/lib/python3.7/dist-packages (from esphome) (5.4.1)                                                   Requirement already satisfied: tornado==6.1 in ./.local/lib/python3.7/site-packages (from esphome) (6.1)                                                        Requirement already satisfied: tzlocal==2.1 in ./.local/lib/python3.7/site-packages (from esphome) (2.1)                                                        Requirement already satisfied: platformio==5.2.0 in ./.local/lib/python3.7/site-packages (from esphome) (5.2.0)                                                 Requirement already satisfied: click==7.1.2 in /usr/local/lib/python3.7/dist-packages (from esphome) (7.1.2)                                                    Requirement already satisfied: esphome-dashboard==20210908.0 in ./.local/lib/python3.7/site-packages (from esphome) (20210908.0)                                Requirement already satisfied: pyserial==3.5 in ./.local/lib/python3.7/site-packages (from esphome) (3.5)                                                       Requirement already satisfied: paho-mqtt==1.5.1 in ./.local/lib/python3.7/site-packages (from esphome) (1.5.1)                                                  Requirement already satisfied: pytz==2021.1 in /usr/local/lib/python3.7/dist-packages (from esphome) (2021.1)                                                   Requirement already satisfied: voluptuous==0.12.1 in ./.local/lib/python3.7/site-packages (from esphome) (0.12.1)                                               Requirement already satisfied: esptool==3.1 in ./.local/lib/python3.7/site-packages (from esphome) (3.1)                                                        Requirement already satisfied: aioesphomeapi==9.1.4 in ./.local/lib/python3.7/site-packages (from esphome) (9.1.4)                                              Requirement already satisfied: starlette==0.16.* in ./.local/lib/python3.7/site-packages (from platformio==5.2.0->esphome) (0.16.0)                             Requirement already satisfied: requests==2.* in ./.local/lib/python3.7/site-packages (from platformio==5.2.0->esphome) (2.26.0)                                 Requirement already satisfied: aiofiles==0.7.* in ./.local/lib/python3.7/site-packages (from platformio==5.2.0->esphome) (0.7.0)                                Requirement already satisfied: wsproto==1.0.* in ./.local/lib/python3.7/site-packages (from platformio==5.2.0->esphome) (1.0.0)                                 Requirement already satisfied: semantic-version==2.8.* in ./.local/lib/python3.7/site-packages (from platformio==5.2.0->esphome) (2.8.5)                        Requirement already satisfied: tabulate==0.8.* in ./.local/lib/python3.7/site-packages (from platformio==5.2.0->esphome) (0.8.9)                                Requirement already satisfied: marshmallow<4,>=2 in ./.local/lib/python3.7/site-packages (from platformio==5.2.0->esphome) (3.15.0)                             Requirement already satisfied: pyelftools<1,>=0.27 in ./.local/lib/python3.7/site-packages (from platformio==5.2.0->esphome) (0.28)                             Requirement already satisfied: zeroconf==0.36.* in ./.local/lib/python3.7/site-packages (from platformio==5.2.0->esphome) (0.36.12)                             Requirement already satisfied: bottle==0.12.* in ./.local/lib/python3.7/site-packages (from platformio==5.2.0->esphome) (0.12.19)                               Requirement already satisfied: ajsonrpc==1.* in ./.local/lib/python3.7/site-packages (from platformio==5.2.0->esphome) (1.2.0)                                  Requirement already satisfied: uvicorn==0.15.* in ./.local/lib/python3.7/site-packages (from platformio==5.2.0->esphome) (0.15.0)                               Requirement already satisfied: bitstring>=3.1.6 in ./.local/lib/python3.7/site-packages (from esptool==3.1->esphome) (3.1.9)                                    Requirement already satisfied: ecdsa>=0.16.0 in ./.local/lib/python3.7/site-packages (from esptool==3.1->esphome) (0.17.0)                                      Requirement already satisfied: reedsolo<=1.5.4,>=1.5.3 in ./.local/lib/python3.7/site-packages (from esptool==3.1->esphome) (1.5.4)                             Requirement already satisfied: cryptography>=2.1.4 in ./.local/lib/python3.7/site-packages (from esptool==3.1->esphome) (3.3.2)                                 Requirement already satisfied: noiseprotocol<1.0,>=0.3.1 in ./.local/lib/python3.7/site-packages (from aioesphomeapi==9.1.4->esphome) (0.3.1)                   Requirement already satisfied: protobuf<4.0,>=3.12.2 in ./.local/lib/python3.7/site-packages (from aioesphomeapi==9.1.4->esphome) (3.20.0)                      Requirement already satisfied: anyio<4,>=3.0.0 in ./.local/lib/python3.7/site-packages (from starlette==0.16.*->platformio==5.2.0->esphome) (3.5.0)             Requirement already satisfied: typing-extensions; python_version < "3.8" in ./.local/lib/python3.7/site-packages (from starlette==0.16.*->platformio==5.2.0->esphome) (4.1.1)                                                                   Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./.local/lib/python3.7/site-packages (from requests==2.*->platformio==5.2.0->esphome) (1.26.9)          Requirement already satisfied: idna<4,>=2.5; python_version >= "3" in /usr/lib/python3/dist-packages (from requests==2.*->platformio==5.2.0->esphome) (2.6)     Requirement already satisfied: charset-normalizer~=2.0.0; python_version >= "3" in ./.local/lib/python3.7/site-packages (from requests==2.*->platformio==5.2.0->esphome) (2.0.12)                                                               Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests==2.*->platformio==5.2.0->esphome) (2018.8.24)                Requirement already satisfied: h11<1,>=0.9.0 in ./.local/lib/python3.7/site-packages (from wsproto==1.0.*->platformio==5.2.0->esphome) (0.13.0)                 Requirement already satisfied: packaging in ./.local/lib/python3.7/site-packages (from marshmallow<4,>=2->platformio==5.2.0->esphome) (21.3)                    Requirement already satisfied: ifaddr>=0.1.7 in /usr/local/lib/python3.7/dist-packages (from zeroconf==0.36.*->platformio==5.2.0->esphome) (0.1.7)              Requirement already satisfied: asgiref>=3.4.0 in ./.local/lib/python3.7/site-packages (from uvicorn==0.15.*->platformio==5.2.0->esphome) (3.5.0)                Requirement already satisfied: six>=1.9.0 in ./.local/lib/python3.7/site-packages (from ecdsa>=0.16.0->esptool==3.1->esphome) (1.16.0)                          Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.7/dist-packages (from cryptography>=2.1.4->esptool==3.1->esphome) (1.14.6)                  Requirement already satisfied: sniffio>=1.1 in ./.local/lib/python3.7/site-packages (from anyio<4,>=3.0.0->starlette==0.16.*->platformio==5.2.0->esphome) (1.2.0)                                                                               Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in ./.local/lib/python3.7/site-packages (from packaging->marshmallow<4,>=2->platformio==5.2.0->esphome) (3.0.7)                                                                         Requirement already satisfied: pycparser in /usr/local/lib/python3.7/dist-packages (from cffi>=1.12->cryptography>=2.1.4->esptool==3.1->esphome) (2.20)`

**Comment by dominikkarall** [comment]
Can you find the file in the directory mentioned above?

**Comment by Ice81** [comment]
Yes, the File esphome is in the Directory.

**Comment by dominikkarall** [comment]
Ok, let's try to run in from command line.

.local/bin/esphome dashboard esphome_config/

Run this from /opt/fhem with user fhem.

**Comment by Ice81** [comment]
OK, I have executed it.
This is what it says in the terminal:
fhem@raspberrypi:~$ .local/bin/esphome dashboard esphome_config/ INFO Starting dashboard web server on port 6052 and configuration dir esphome_config/...
Übersetzt mit DeepL https://www.deepl.com/app/?utm_medium=android-share

**Comment by dominikkarall** [comment]
Hmm...so it seems to work. Stop it please and do
set esphome stop
set esphome start

After that check if the process is running, if not, check the fhem and fhempy log.

**Comment by Ice81** [comment]
I have done everything.
Unfortunately without success.

I cannot open a log file from Fhempy via fhem (it is empty).

Einfach kann ja jeder :-)

**Comment by Ice81** [comment]
When I run .local/bin/esphome dashboard esphome_config/, I can access the esphome Dashboard web interface via the web browser under Raspberrypi:6052. This is already a great success for me

**Comment by Ice81** [comment]
Perhaps this will also help,
When I click on the ESP home web interface, the following information and errors appear in the terminal:
`fhem@raspberrypi:~$ .local/bin/esphome dashboard esphome_config/                INFO Starting dashboard web server on port 6052 and configuration dir esphome_config/...                                                                        INFO 304 GET / (192.168.178.15) 54.27ms                                         INFO 200 GET /static/fonts/material-icons/material-icons.css?hash=ead4c276 (192.168.178.15) 11.80ms                                                             INFO 200 GET /static/js/vendor/jquery-validate/jquery.validate.min.js?hash=aad785d4 (192.168.178.15) 7.47ms                                                     INFO 200 GET /static/css/esphome.css?hash=2ea4c658 (192.168.178.15) 18.41ms     INFO 200 GET /static/css/vendor/materialize/materialize.min.css?hash=ec1df3ba (192.168.178.15) 55.17ms                                                          INFO 200 GET /static/js/vendor/jquery/jquery.min.js?hash=12108007 (192.168.178.15) 36.40ms                                                                      INFO 200 GET /static/js/vendor/materialize/materialize.min.js?hash=4be20daf (192.168.178.15) 57.45ms                                                            INFO 200 GET /static/js/vendor/jquery-ui/jquery-ui.min.js?hash=cab3392d (192.168.178.15) 62.95ms                                                                INFO 200 GET /static/js/esphome/index-9a842255.js (192.168.178.15) 1.86ms       INFO 200 GET /static/js/vendor/ace/ace.js?hash=65322f49 (192.168.178.15) 36.81msINFO 200 GET /static/fonts/material-icons/MaterialIcons-Regular.woff2 (192.168.178.15) 3.12ms                                                                   INFO 200 GET /static/js/vendor/ace/theme-dreamweaver.js (192.168.178.15) 2.13ms INFO 200 GET /static/js/vendor/ace/mode-yaml.js (192.168.178.15) 3.04ms         INFO 101 GET /ace (192.168.178.15) 1.18ms                                       INFO Running command 'esphome --dashboard -q vscode --ace esphome_config/'      ERROR Uncaught exception GET /ace (192.168.178.15)                              HTTPServerRequest(protocol='http', host='raspberrypi:6052', method='GET', uri='/ace', version='HTTP/1.1', remote_ip='192.168.178.15')                           Traceback (most recent call last):                                                File "/opt/fhem/.local/lib/python3.7/site-packages/tornado/websocket.py", line 647, in _run_callback                                                              result = callback(*args, **kwargs)                                            File "/opt/fhem/.local/lib/python3.7/site-packages/esphome/dashboard/dashboard.py", line 134, in decorator                                                        return func(self, *args, **kwargs)                                            File "/opt/fhem/.local/lib/python3.7/site-packages/esphome/dashboard/dashboard.py", line 212, in on_message                                                       handlers[type_](self, json_message)                                           File "/opt/fhem/.local/lib/python3.7/site-packages/esphome/dashboard/dashboard.py", line 225, in handle_spawn                                                     stdin=tornado.process.Subprocess.STREAM,                                      File "/opt/fhem/.local/lib/python3.7/site-packages/tornado/process.py", line 240, in __init__                                                                     self.proc = subprocess.Popen(*args, **kwargs)                                 File "/usr/lib/python3.7/subprocess.py", line 775, in __init__                    restore_signals, start_new_session)                                           File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child             raise child_exception_type(errno_num, err_msg, err_filename)                FileNotFoundError: [Errno 2] No such file or directory: 'esphome': 'esphome'    INFO 200 GET /static/images/favicon.ico?hash=2655a073 (192.168.178.15) 3.10ms   INFO 101 GET /ace (192.168.178.15) 2.98ms                                       INFO Running command 'esphome --dashboard -q vscode --ace esphome_config/'      ERROR Uncaught exception GET /ace (192.168.178.15)                              HTTPServerRequest(protocol='http', host='raspberrypi:6052', method='GET', uri='/ace', version='HTTP/1.1', remote_ip='192.168.178.15')                           Traceback (most recent call last):                                                File "/opt/fhem/.local/lib/python3.7/site-packages/tornado/websocket.py", line 647, in _run_callback                                                              result = callback(*args, **kwargs)                                            File "/opt/fhem/.local/lib/python3.7/site-packages/esphome/dashboard/dashboard.py", line 134, in decorator                                                        return func(self, *args, **kwargs)                                            File "/opt/fhem/.local/lib/python3.7/site-packages/esphome/dashboard/dashboard.py", line 212, in on_message                                                       handlers[type_](self, json_message)                                           File "/opt/fhem/.local/lib/python3.7/site-packages/esphome/dashboard/dashboard.py", line 225, in handle_spawn                                                     stdin=tornado.process.Subprocess.STREAM,                                      File "/opt/fhem/.local/lib/python3.7/site-packages/tornado/process.py", line 240, in __init__                                                                     self.proc = subprocess.Popen(*args, **kwargs)                                 File "/usr/lib/python3.7/subprocess.py", line 775, in __init__                    restore_signals, start_new_session)                                           File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child             raise child_exception_type(errno_num, err_msg, err_filename)                FileNotFoundError: [Errno 2] No such file or directory: 'esphome': 'esphome'    INFO 101 GET /ace (192.168.178.15) 2.52ms                                       INFO Running command 'esphome --dashboard -q vscode --ace esphome_config/'      ERROR Uncaught exception GET /ace (192.168.178.15)                              HTTPServerRequest(protocol='http', host='raspberrypi:6052', method='GET', uri='/ace', version='HTTP/1.1', remote_ip='192.168.178.15')                           Traceback (most recent call last):                                                File "/opt/fhem/.local/lib/python3.7/site-packages/tornado/websocket.py", line 647, in _run_callback                                                              result = callback(*args, **kwargs)                                            File "/opt/fhem/.local/lib/python3.7/site-packages/esphome/dashboard/dashboard.py", line 134, in decorator                                                        return func(self, *args, **kwargs)                                            File "/opt/fhem/.local/lib/python3.7/site-packages/esphome/dashboard/dashboard.py", line 212, in on_message                                                       handlers[type_](self, json_message)                                           File "/opt/fhem/.local/lib/python3.7/site-packages/esphome/dashboard/dashboard.py", line 225, in handle_spawn                                                     stdin=tornado.process.Subprocess.STREAM,                                      File "/opt/fhem/.local/lib/python3.7/site-packages/tornado/process.py", line 240, in __init__                                                                     self.proc = subprocess.Popen(*args, **kwargs)                                 File "/usr/lib/python3.7/subprocess.py", line 775, in __init__                    restore_signals, start_new_session)                                           File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child             raise child_exception_type(errno_num, err_msg, err_filename)                FileNotFoundError: [Errno 2] No such file or directory: 'esphome': 'esphome'    ^CINFO Shutting down...                                                         fhem@raspberrypi:~$`

**Comment by dominikkarall** [comment]
Sorry for my late response.

I found the bug and fixed it in the latest version. Just update fhempy update (set fhempy_local update) and wait a few minutes. Afterwards check again if it works.

Please let me know if it works for you.

**Comment by Ice81** [comment]
No problem at all, it's the weekend.
The problem is solved. 
It now works without any problems.
Thank you very much for your help.
Now I just have to get my flashed bed side lamp into the ESPHome.
