### ISSUE TITLE
Latest stable version 0.1.348

### ISSUE THREAD

**Issue by jfmennedy** [dominikkarall/fhempy#79]
Hi Dominik,

the latest updates from 0.1.348 to 357 result in none proper start. I tried several restarts and switched back to 348 now.

these are the log entries while starting 357:

Mai 22 21:11:07 pi fhempy[472]: 2022-05-22 21:11:07,590 - INFO     - fhempy.lib.fhem_pythonbinding: Starting fhempy 0.1.357...
Mai 22 21:11:07 pi fhempy[472]: 2022-05-22 21:11:07,594 - INFO     - fhempy.lib.fhem_pythonbinding: Advertise fhempy on local network
Mai 22 21:11:07 pi fhempy[472]: 2022-05-22 21:11:07,983 - INFO     - fhempy.lib.fhem_pythonbinding: Waiting for FHEM connection
Mai 22 21:11:08 pi fhempy[472]: 2022-05-22 21:11:08,072 - INFO     - websockets.server: server listening on 0.0.0.0:15733
Mai 22 21:11:09 pi fhempy[472]: 2022-05-22 21:11:09,731 - INFO     - websockets.server: connection open
Mai 22 21:11:09 pi fhempy[472]: 2022-05-22 21:11:09,734 - INFO     - fhempy.lib.fhem_pythonbinding: Incoming FHEM connection: 192.168.0.249
Mai 22 21:11:11 pi fhempy[472]: 2022-05-22 21:11:11,278 - WARNING  - asyncio: Executing <Task pending name='Task-91' coro=<fhempy.onMessage() running at /home/pi/.local/lib/python3.9/site-packages/fhempy/lib/fhem_pythonbinding.py:144> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.9/asyncio/futures.py:384, <TaskWakeupMethWrapper obj>
Mai 22 21:11:14 pi fhempy[472]: 2022-05-22 21:11:14,807 - INFO     - skodaconnect.connection: Init Skoda Connect library, version 1.1.19
Mai 22 21:11:14 pi fhempy[472]: 2022-05-22 21:11:14,809 - INFO     - skodaconnect.connection: Initiating new login
Mai 22 21:11:15 pi fhempy[472]: 2022-05-22 21:11:15,275 - WARNING  - asyncio: Executing <Task pending name='Task-274' coro=<spotify.connect_spotipy() running at /home/pi/.local/lib/python3.9/site-packages/fhempy/lib/spotify/spotify.py:218> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/lib/python3.9/asyncio/futures.py:384, <TaskWakeupMethWrappe>
Mai 22 21:11:16 pi fhempy[472]: 2022-05-22 21:11:16,843 - ERROR    - spoti_Julia: Failed to update status
Mai 22 21:11:16 pi fhempy[472]: Traceback (most recent call last):
Mai 22 21:11:16 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/requests/models.py", line 910, in json
Mai 22 21:11:16 pi fhempy[472]:     return complexjson.loads(self.text, **kwargs)
Mai 22 21:11:16 pi fhempy[472]:   File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
Mai 22 21:11:16 pi fhempy[472]:     return _default_decoder.decode(s)
Mai 22 21:11:16 pi fhempy[472]:   File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
Mai 22 21:11:16 pi fhempy[472]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Mai 22 21:11:16 pi fhempy[472]:   File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
Mai 22 21:11:16 pi fhempy[472]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Mai 22 21:11:16 pi fhempy[472]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Mai 22 21:11:16 pi fhempy[472]: During handling of the above exception, another exception occurred:
Mai 22 21:11:16 pi fhempy[472]: Traceback (most recent call last):
Mai 22 21:11:16 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/spotipy/client.py", line 246, in _internal_call
Mai 22 21:11:16 pi fhempy[472]:     results = response.json()
Mai 22 21:11:16 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/requests/models.py", line 917, in json
Mai 22 21:11:16 pi fhempy[472]:     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
Mai 22 21:11:16 pi fhempy[472]: requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0
Mai 22 21:11:16 pi fhempy[472]: During handling of the above exception, another exception occurred:
Mai 22 21:11:16 pi fhempy[472]: Traceback (most recent call last):
Mai 22 21:11:16 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/spotify/spotify.py", line 341, in update_playback
Mai 22 21:11:16 pi fhempy[472]:     status = await utils.run_blocking(
Mai 22 21:11:16 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/utils.py", line 34, in run_blocking
Mai 22 21:11:16 pi fhempy[472]:     return await asyncio.get_event_loop().run_in_executor(pool, function)
Mai 22 21:11:16 pi fhempy[472]:   File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Mai 22 21:11:16 pi fhempy[472]:     result = self.fn(*self.args, **self.kwargs)
Mai 22 21:11:16 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/spotipy/client.py", line 1703, in current_playback
Mai 22 21:11:16 pi fhempy[472]:     return self._get("me/player", market=market, additional_types=additional_types)
Mai 22 21:11:16 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/spotipy/client.py", line 297, in _get
Mai 22 21:11:16 pi fhempy[472]:     return self._internal_call("GET", url, payload, kwargs)
Mai 22 21:11:16 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/spotipy/client.py", line 247, in _internal_call
Mai 22 21:11:16 pi fhempy[472]:     except requests.exceptions.HTTPError as http_error:
Mai 22 21:11:16 pi fhempy[472]: AttributeError: module 'requests' has no attribute 'exceptions'
Mai 22 21:11:18 pi fhempy[472]: 2022-05-22 21:11:18,571 - WARNING  - asyncio: Executing <Task pending name='Task-192' coro=<ring.ring_login() running at /home/pi/.local/lib/python3.9/site-packages/fhempy/lib/ring/ring.py:110> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f66aa5aed00>()] created at /usr/lib/python3.9/asyncio/base_events.py:424> cb=[FhemModule.>
Mai 22 21:11:19 pi fhempy[472]: 2022-05-22 21:11:19,973 - ERROR    - wzKonvektor: Failed create_device
Mai 22 21:11:19 pi fhempy[472]: Traceback (most recent call last):
Mai 22 21:11:19 pi fhempy[472]:   File "/usr/lib/python3.9/asyncio/locks.py", line 413, in acquire
Mai 22 21:11:19 pi fhempy[472]:     await fut
Mai 22 21:11:19 pi fhempy[472]: asyncio.exceptions.CancelledError
Mai 22 21:11:19 pi fhempy[472]: During handling of the above exception, another exception occurred:
Mai 22 21:11:19 pi fhempy[472]: Traceback (most recent call last):
Mai 22 21:11:19 pi fhempy[472]:   File "/usr/lib/python3.9/asyncio/tasks.py", line 492, in wait_for
Mai 22 21:11:19 pi fhempy[472]:     fut.result()
Mai 22 21:11:19 pi fhempy[472]: asyncio.exceptions.CancelledError
Mai 22 21:11:19 pi fhempy[472]: The above exception was the direct cause of the following exception:
Mai 22 21:11:19 pi fhempy[472]: Traceback (most recent call last):
Mai 22 21:11:19 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 405, in create_device
Mai 22 21:11:19 pi fhempy[472]:     await self._create_mapping_dev()
Mai 22 21:11:19 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/tuya.py", line 130, in _create_mapping_dev
Mai 22 21:11:19 pi fhempy[472]:     status = await self._connected_device.status()
Mai 22 21:11:19 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/pytuya/__init__.py", line 481, in status
Mai 22 21:11:19 pi fhempy[472]:     status = await self.exchange(STATUS)
Mai 22 21:11:19 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/pytuya/__init__.py", line 460, in exchange
Mai 22 21:11:19 pi fhempy[472]:     msg = await self.dispatcher.wait_for(seqno)
Mai 22 21:11:19 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/tuya/pytuya/__init__.py", line 247, in wait_for
Mai 22 21:11:19 pi fhempy[472]:     await asyncio.wait_for(self.listeners[seqno].acquire(), timeout=timeout)
Mai 22 21:11:19 pi fhempy[472]:   File "/usr/lib/python3.9/asyncio/tasks.py", line 494, in wait_for
Mai 22 21:11:19 pi fhempy[472]:     raise exceptions.TimeoutError() from exc
Mai 22 21:11:19 pi fhempy[472]: asyncio.exceptions.TimeoutError
Mai 22 21:11:20 pi fhempy[472]: 2022-05-22 21:11:20,637 - WARNING  - asyncio: Executing <Task pending name='Task-192' coro=<ring.ring_login() running at /home/pi/.local/lib/python3.9/site-packages/fhempy/lib/ring/ring.py:110> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f66f5ad8d90>()] created at /usr/lib/python3.9/asyncio/base_events.py:424> cb=[FhemModule.>
Mai 22 21:12:08 pi fhempy[472]: 2022-05-22 21:12:08,875 - ERROR    - fhempy.lib.fhem: Timeout - NO RESPONSE for command: foreach my $fhem_dev (sort keys %main::defs) {  return 1 if(defined($main::defs{$fhem_dev}{TYPE}) && $main::defs{$fhem_dev}{TYPE} eq 'BindingsIo' && $main::defs{$fhem_dev}{IP} eq '192.168.0.173');;}return 0;;
Mai 22 21:12:16 pi fhempy[472]: 2022-05-22 21:12:16,017 - ERROR    - spoti_Julia: Failed to update status
Mai 22 21:12:16 pi fhempy[472]: Traceback (most recent call last):
Mai 22 21:12:16 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/requests/models.py", line 910, in json
Mai 22 21:12:16 pi fhempy[472]:     return complexjson.loads(self.text, **kwargs)
Mai 22 21:12:16 pi fhempy[472]:   File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
Mai 22 21:12:16 pi fhempy[472]:     return _default_decoder.decode(s)
Mai 22 21:12:16 pi fhempy[472]:   File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
Mai 22 21:12:16 pi fhempy[472]:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
Mai 22 21:12:16 pi fhempy[472]:   File "/usr/lib/python3.9/json/decoder.py", line 355, in raw_decode
Mai 22 21:12:16 pi fhempy[472]:     raise JSONDecodeError("Expecting value", s, err.value) from None
Mai 22 21:12:16 pi fhempy[472]: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Mai 22 21:12:16 pi fhempy[472]: During handling of the above exception, another exception occurred:
Mai 22 21:12:16 pi fhempy[472]: Traceback (most recent call last):
Mai 22 21:12:16 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/spotipy/client.py", line 246, in _internal_call
Mai 22 21:12:16 pi fhempy[472]:     results = response.json()
Mai 22 21:12:16 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/requests/models.py", line 917, in json
Mai 22 21:12:16 pi fhempy[472]:     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
Mai 22 21:12:16 pi fhempy[472]: requests.exceptions.JSONDecodeError: [Errno Expecting value] : 0
Mai 22 21:12:16 pi fhempy[472]: During handling of the above exception, another exception occurred:
Mai 22 21:12:16 pi fhempy[472]: Traceback (most recent call last):
Mai 22 21:12:16 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/spotify/spotify.py", line 341, in update_playback
Mai 22 21:12:16 pi fhempy[472]:     status = await utils.run_blocking(
Mai 22 21:12:16 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/fhempy/lib/utils.py", line 34, in run_blocking
Mai 22 21:12:16 pi fhempy[472]:     return await asyncio.get_event_loop().run_in_executor(pool, function)
Mai 22 21:12:16 pi fhempy[472]:   File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
Mai 22 21:12:16 pi fhempy[472]:     result = self.fn(*self.args, **self.kwargs)
Mai 22 21:12:16 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/spotipy/client.py", line 1703, in current_playback
Mai 22 21:12:16 pi fhempy[472]:     return self._get("me/player", market=market, additional_types=additional_types)
Mai 22 21:12:16 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/spotipy/client.py", line 297, in _get
Mai 22 21:12:16 pi fhempy[472]:     return self._internal_call("GET", url, payload, kwargs)
Mai 22 21:12:16 pi fhempy[472]:   File "/home/pi/.local/lib/python3.9/site-packages/spotipy/client.py", line 247, in _internal_call
Mai 22 21:12:16 pi fhempy[472]:     except requests.exceptions.HTTPError as http_error:
Mai 22 21:12:16 pi fhempy[472]: AttributeError: module 'requests' has no attribute 'exceptions'

**Comment by dominikkarall** [comment]
Can you try version 354 please? I think it is related to the library updates.

**Comment by jfmennedy** [comment]
with 354 it is working...

**Comment by dominikkarall** [comment]
Thanks for testing! So it must be one of the library updates. I'll downgrade them today in the evening.

**Comment by jfmennedy** [comment]
358 is working for me...

**Comment by dominikkarall** [comment]
Closed. I'm going to update the libraries one by one and skip the requests update in the meantime.
