### ISSUE TITLE
Contribution question

### ISSUE THREAD

**Issue by ole1986** [dominikkarall/fhempy#8]
I am just asking myself how to contribute to this great project.

Just trying to amend the castdevice modul but could not get it to recompile/restart to make my ne "features" available.

Any idea what needs to get restarted or reloaded to make the code changes available?

Thank you in advance

**Comment by dominikkarall** [comment]
Would be great if you could contribute!

To do testing during development you can do following steps:
 - Edit the project in VS Code (it's my favorite editor, use one of your choice)
 - Copy edited files to /opt/fhem/FHEM/bindings/python/...
 - Restart Pythonbinding_15733 (or just do a killall python3 it automatically restarts)
 - `tail -f /opt/fhem/log/PythonBinding-....` to see what happens
 - Wait till FHEM reconnects and after that check the new features

You might also do remote development by running fhempy on your development environment and connect to that one from FHEM:
 - Run `dominik@penguin:~/vsc-github/fhempy$ FHEM/bindings/python/bin/fhempy`, be aware to run it from fhempy directory
 - FHEM: `define development_peer BindingsIo IP:15733 Python` where IP is your development machine IP address

**Comment by dominikkarall** [comment]
I added some .vscode configuration files to make it easier to start with programming. If you need help, let me know.

Closing due to no more updates. If you have any issues, feel free to open a new issue.

**Comment by ole1986** [comment]
Thank you,
