### ISSUE TITLE
BindingsIo (fhempy_local): ERROR fhempy_local 

### ISSUE THREAD

**Issue by olgo59** [dominikkarall/fhempy#82]
Hallo,
leider bekomme ich den Service nicht ans laufen.
Ich habe folgende Fehlermeldung:
BindingsIo (fhempy_local): ERROR fhempy_local - error while connecting: 127.0.0.1: Verbindungsaufbau abgelehnt (111)

Anbei meine log Einträge
fhempy.log
2022-06-02 10:30:47,544 - ERROR    - __main__: Unable to install package fhempy>=0.1.12: error: subprocess-exited-with-error

  × Building wheel for cryptography (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [162 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-i686-cpython-39
      creating build/lib.linux-i686-cpython-39/cryptography
      copying src/cryptography/exceptions.py -> build/lib.linux-i686-cpython-39/cryptography
      copying src/cryptography/__init__.py -> build/lib.linux-i686-cpython-39/cryptography
      copying src/cryptography/utils.py -> build/lib.linux-i686-cpython-39/cryptography
      copying src/cryptography/fernet.py -> build/lib.linux-i686-cpython-39/cryptography
      copying src/cryptography/__about__.py -> build/lib.linux-i686-cpython-39/cryptography
      creating build/lib.linux-i686-cpython-39/cryptography/hazmat
      copying src/cryptography/hazmat/__init__.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat
      copying src/cryptography/hazmat/_types.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat
      copying src/cryptography/hazmat/_oid.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat
      copying src/cryptography/hazmat/_der.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat
      creating build/lib.linux-i686-cpython-39/cryptography/x509
      copying src/cryptography/x509/base.py -> build/lib.linux-i686-cpython-39/cryptography/x509
      copying src/cryptography/x509/certificate_transparency.py -> build/lib.linux-i686-cpython-39/cryptography/x509
      copying src/cryptography/x509/__init__.py -> build/lib.linux-i686-cpython-39/cryptography/x509
      copying src/cryptography/x509/extensions.py -> build/lib.linux-i686-cpython-39/cryptography/x509
      copying src/cryptography/x509/general_name.py -> build/lib.linux-i686-cpython-39/cryptography/x509
      copying src/cryptography/x509/oid.py -> build/lib.linux-i686-cpython-39/cryptography/x509
      copying src/cryptography/x509/ocsp.py -> build/lib.linux-i686-cpython-39/cryptography/x509
      copying src/cryptography/x509/name.py -> build/lib.linux-i686-cpython-39/cryptography/x509
      creating build/lib.linux-i686-cpython-39/cryptography/hazmat/backends
      copying src/cryptography/hazmat/backends/interfaces.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends
      copying src/cryptography/hazmat/backends/__init__.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends
      creating build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/keywrap.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/cmac.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/__init__.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/poly1305.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/padding.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/_cipheralgorithm.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/hashes.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/constant_time.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/_serialization.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/_asymmetric.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives
      copying src/cryptography/hazmat/primitives/hmac.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives
      creating build/lib.linux-i686-cpython-39/cryptography/hazmat/bindings
      copying src/cryptography/hazmat/bindings/__init__.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/bindings
      creating build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/encode_asn1.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/x509.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/cmac.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/x448.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/__init__.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/backend.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/x25519.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/poly1305.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/utils.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/rsa.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/ed25519.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/ec.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/ed448.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/aead.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/decode_asn1.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/dh.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/hashes.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/dsa.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/ciphers.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/ocsp.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      copying src/cryptography/hazmat/backends/openssl/hmac.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/backends/openssl
      creating build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/kdf
      copying src/cryptography/hazmat/primitives/kdf/pbkdf2.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/kdf
      copying src/cryptography/hazmat/primitives/kdf/kbkdf.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/kdf
      copying src/cryptography/hazmat/primitives/kdf/__init__.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/kdf
      copying src/cryptography/hazmat/primitives/kdf/x963kdf.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/kdf
      copying src/cryptography/hazmat/primitives/kdf/concatkdf.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/kdf
      copying src/cryptography/hazmat/primitives/kdf/scrypt.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/kdf
      copying src/cryptography/hazmat/primitives/kdf/hkdf.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/kdf
      creating build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/ciphers
      copying src/cryptography/hazmat/primitives/ciphers/base.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/ciphers
      copying src/cryptography/hazmat/primitives/ciphers/__init__.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/ciphers
      copying src/cryptography/hazmat/primitives/ciphers/modes.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/ciphers
      copying src/cryptography/hazmat/primitives/ciphers/aead.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/ciphers
      copying src/cryptography/hazmat/primitives/ciphers/algorithms.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/ciphers
      creating build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/x448.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/__init__.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/x25519.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/utils.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/rsa.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/ed25519.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/ec.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/ed448.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/padding.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/dh.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/asymmetric
      copying src/cryptography/hazmat/primitives/asymmetric/dsa.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/asymmetric
      creating build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/serialization
      copying src/cryptography/hazmat/primitives/serialization/base.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/serialization
      copying src/cryptography/hazmat/primitives/serialization/pkcs12.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/serialization
      copying src/cryptography/hazmat/primitives/serialization/__init__.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/serialization
      copying src/cryptography/hazmat/primitives/serialization/ssh.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/serialization
      copying src/cryptography/hazmat/primitives/serialization/pkcs7.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/serialization
      creating build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/twofactor
      copying src/cryptography/hazmat/primitives/twofactor/hotp.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/twofactor
      copying src/cryptography/hazmat/primitives/twofactor/totp.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/twofactor
      copying src/cryptography/hazmat/primitives/twofactor/__init__.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/twofactor
      copying src/cryptography/hazmat/primitives/twofactor/utils.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/primitives/twofactor
      creating build/lib.linux-i686-cpython-39/cryptography/hazmat/bindings/openssl
      copying src/cryptography/hazmat/bindings/openssl/__init__.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/bindings/openssl
      copying src/cryptography/hazmat/bindings/openssl/binding.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/bindings/openssl
      copying src/cryptography/hazmat/bindings/openssl/_conditional.py -> build/lib.linux-i686-cpython-39/cryptography/hazmat/bindings/openssl
      running egg_info
      writing src/cryptography.egg-info/PKG-INFO
      writing dependency_links to src/cryptography.egg-info/dependency_links.txt
      writing requirements to src/cryptography.egg-info/requires.txt
      writing top-level names to src/cryptography.egg-info/top_level.txt
      reading manifest file 'src/cryptography.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      no previously-included directories found matching 'docs/_build'
      warning: no previously-included files found matching 'vectors'
      warning: no previously-included files matching '*' found under directory 'vectors'
      warning: no previously-included files matching '*' found under directory '.github'
      warning: no previously-included files found matching 'release.py'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'dev-requirements.txt'
      warning: no previously-included files found matching 'tox.ini'
      warning: no previously-included files found matching 'mypy.ini'
      warning: no previously-included files matching '*' found under directory '.zuul.d'
      warning: no previously-included files matching '*' found under directory '.zuul.playbooks'
      adding license file 'LICENSE'
      adding license file 'LICENSE.APACHE'
      adding license file 'LICENSE.BSD'
      adding license file 'LICENSE.PSF'
      writing manifest file 'src/cryptography.egg-info/SOURCES.txt'
      copying src/cryptography/py.typed -> build/lib.linux-i686-cpython-39/cryptography
      running build_ext
      running build_rust

          =============================DEBUG ASSISTANCE=============================
          If you are seeing a compilation error please try the following steps to
          successfully install cryptography:
          1) Upgrade to the latest pip and try again. This will fix errors for most
             users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
          2) Read https://cryptography.io/en/latest/installation.html for specific
             instructions for your platform.
          3) Check our frequently asked questions for more information:
             https://cryptography.io/en/latest/faq.html
          4) Ensure you have a recent Rust toolchain installed:
             https://cryptography.io/en/latest/installation.html#rust
          5) If you are experiencing issues with Rust for *this release only* you may
             set the environment variable `CRYPTOGRAPHY_DONT_BUILD_RUST=1`.
          =============================DEBUG ASSISTANCE=============================

      error: can't find Rust compiler

      If you are using an outdated pip version, it is possible a prebuilt wheel is available for this package but pip is not able to install from it. Installing from the wheel would avoid the need for a Rust compiler.

      To update pip, run:

          pip install --upgrade pip

      and then retry package installation.

      If you did intend to build this package from source, try installing a Rust compiler from your system package manager and ensure it is on the PATH during installation. Alternatively, rustup (available at https://rustup.rs) is the recommended way to download and update the Rust compiler toolchain.

      This package requires Rust >=1.41.0.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cryptography
ERROR: Could not build wheels for cryptography, which is required to install pyproject.toml-based projects
2022-06-02 10:30:47,545 - ERROR    - __main__: Failed to install fhempy, exit now...
2022-06-02 10:31:47,779 - ERROR    - __main__: Failed to load fhempy
Traceback (most recent call last):
  File "/opt/fhem/FHEM/bindings/python/bin/fhempy", line 100, in <module>
    import fhempy.lib.fhem_pythonbinding as fpb
ModuleNotFoundError: No module named 'fhempy'

#fhem.log
2022.06.02 10:29:55 1: BindingsIo (fhempy_local): ERROR fhempy_local - error while connecting: 127.0.0.1: Verbindungsaufbau abgelehnt (111)
2022.06.02 10:30:05 1: BindingsIo (fhempy_local): ERROR fhempy_local - error while connecting: 127.0.0.1: Verbindungsaufbau abgelehnt (111)
2022.06.02 10:30:16 1: BindingsIo (fhempy_local): ERROR fhempy_local - error while connecting: 127.0.0.1: Verbindungsaufbau abgelehnt (111)
2022.06.02 10:30:27 1: BindingsIo (fhempy_local): ERROR fhempy_local - error while connecting: 127.0.0.1: Verbindungsaufbau abgelehnt (111)
2022.06.02 10:30:37 1: BindingsIo (fhempy_local): ERROR fhempy_local - error while connecting: 127.0.0.1: Verbindungsaufbau abgelehnt (111)
2022.06.02 10:30:47 1: BindingsIo (fhempy_local): ERROR fhempy_local - error while connecting: 127.0.0.1: Verbindungsaufbau abgelehnt (111)
2022.06.02 10:30:58 1: BindingsIo (fhempy_local): ERROR fhempy_local - error while connecting: 127.0.0.1: Verbindungsaufbau abgelehnt (111)
2022.06.02 10:31:08 1: BindingsIo (fhempy_local): ERROR fhempy_local - error while connecting: 127.0.0.1: Verbindungsaufbau abgelehnt (111)
2022.06.02 10:31:19 1: BindingsIo (fhempy_local): ERROR fhempy_local - error while connecting: 127.0.0.1: Verbindungsaufbau abgelehnt (111)
2022.06.02 10:31:29 1: BindingsIo (fhempy_local): ERROR fhempy_local - error while connecting: 127.0.0.1: Verbindungsaufbau abgelehnt (111)
2022.06.02 10:31:40 1: BindingsIo (fhempy_local): ERROR fhempy_local - error while connecting: 127.0.0.1: Verbindungsaufbau abgelehnt (111)
2022.06.02 10:31:47 3: fhempyserver_15733: read: end of file reached while sysread
2022.06.02 10:31:47 3: fhempyserver_15733: stopped
2022.06.02 10:31:47 3: fhempyserver_15733: starting
2022.06.02 10:31:47 3: fhempyserver_15733: using logfile: ./log/fhempy-2022-06-02.log

#Systeminfos
defmod fhempyserver_15733 fhempyServer 0
attr fhempyserver_15733 devStateIcon {      my $status_img = "10px-kreis-gruen";;;;      my $status_txt = "running";;;;      if (substr(ReadingsVal($name, "fhempy", "running"),0,7) ne "running") {        $status_img = "10px-kreis-rot";;;;        $status_txt = "stopped";;;;      }      "<div><a>".FW_makeImage($status_img, $status_txt)."</a><a  href=\"/fhem?cmd.dummy=set $name restart&XHR=1\" title=\"Restart\">".FW_makeImage("audio_repeat")."</a></div>"      }
attr fhempyserver_15733 group fhempy
attr fhempyserver_15733 icon python
attr fhempyserver_15733 logfile ./log/fhempy-%Y-%m-%d.log
attr fhempyserver_15733 nrarchive 10
attr fhempyserver_15733 room fhempy

setstate fhempyserver_15733 2022-06-02 10:39:39 fhempy running FHEM/bindings/python/bin/fhempy
setstate fhempyserver_15733 2022-06-01 20:43:28 python v3.9.2

defmod fhempy_local BindingsIo fhempy
attr fhempy_local devStateIcon {      my $status_img = "10px-kreis-gruen";;;;      my $status_txt = "connected";;;;      if (ReadingsVal($name, "state", "disconnected") eq "disconnected") {        $status_img = "10px-kreis-rot";;;;        $status_txt = "disconnected";;;;      }      my $ver = ReadingsVal($name, "version", "-");;;;      "<div><a>".FW_makeImage($status_img, $status_txt)."</a><a> ".$ver." </a><a  href=\"/fhem?cmd.dummy=set $name update&XHR=1\" title=\"Start update\">".FW_makeImage("refresh")."</a></div>"    }
attr fhempy_local group fhempy
attr fhempy_local icon file_json-ld2
attr fhempy_local room fhempy

setstate fhempy_local disconnected
setstate fhempy_local 2022-06-02 10:41:02 state disconnected

Kannst Du mir auf Basis dieser Informationen helfen?

Bereits jetzt vielen Dank
Olaf

**Comment by olgo59** [comment]
Der Hinweis vom Dominik
sudo -u fhem bash
pip3 install fhempy==0.1.160

im Fhem Forum
https://forum.fhem.de/index.php/topic,116455.msg1183076.html#msg1183076

Hat geholfen und nun läuft es.

VG
Olaf

**Comment by dominikkarall** [comment]
Hi Olaf,

funktioniert es auch wenn du ein Update von fhempy machst? Wenn nicht, mach das Issue bitte nochmals auf.

**Comment by olgo59** [comment]
Hallo,
update auf 0.1.360 hat funktioniert und ich habe weiter alle Funktionen!
Vielen Dank

:-) Kannst Du mir ggf. auch noch bei dem Zugriff auf ein bestimmtes Device helfen?

**Comment by dominikkarall** [comment]
Bitte dazu ein neues Issue aufmachen.
